_wandb:
    value:
        cli_version: 0.23.1
        e:
            th1qj5hfnc3d9vbb5h1u4xld0fq1lyly:
                args:
                    - --base_model_path
                    - Qwen/Qwen3-1.7B
                    - --train_data_path
                    - ./dataset/train/train_part1.txt
                    - --valid_data_path
                    - ./dataset/val/val.txt
                    - --output_dir
                    - ./outputs/smoke_test-part1
                    - --run_name
                    - smoke_test-part1
                    - --wandb_project
                    - qwen-mt
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1081101176832"
                        used: "64862949376"
                email: tranthaiduong.dtt@gmail.com
                executable: /home/tranduong/qwen-mt-finetune/.venv/bin/python3
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-9d068952-5824-8c6c-f4c5-84edee332336
                host: LAPTOP-CIR1GBE3
                memory:
                    total: "7988244480"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/tranduong/qwen-mt-finetune/train.py
                python: CPython 3.11.14
                root: /home/tranduong/qwen-mt-finetune
                startedAt: "2025-12-14T06:47:42.979898Z"
                writerId: th1qj5hfnc3d9vbb5h1u4xld0fq1lyly
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 98
            "3":
                - 13
            "4": 3.11.14
            "5": 0.23.1
            "6": 4.57.3
            "12": 0.23.1
            "13": linux-x86_64
