_wandb:
    value:
        cli_version: 0.23.1
        e:
            54in16ccryzomt0t1ezhnd8zsyhufs6o:
                args:
                    - --base_model_path
                    - Qwen/Qwen3-1.7B
                    - --adapter_model_path
                    - outputs/smoke_test-part1/best_model
                    - --test_data_path
                    - dataset/medical-vlsp-2025/test/test_all.txt
                    - --run_name
                    - smoke_test-part1-eval
                    - --wandb_project
                    - qwen-mt
                    - --max_test_samples
                    - "10"
                codePath: evaluate.py
                codePathLocal: evaluate.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1081101176832"
                        used: "70033866752"
                email: tranthaiduong.dtt@gmail.com
                executable: /home/tranduong/qwen-mt-finetune/.venv/bin/python
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-9d068952-5824-8c6c-f4c5-84edee332336
                host: LAPTOP-CIR1GBE3
                memory:
                    total: "7988244480"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/tranduong/qwen-mt-finetune/evaluate.py
                python: CPython 3.11.14
                root: /home/tranduong/qwen-mt-finetune
                startedAt: "2025-12-14T07:08:07.076292Z"
                writerId: 54in16ccryzomt0t1ezhnd8zsyhufs6o
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 9
                - 11
                - 49
                - 71
                - 98
                - 103
            "2":
                - 1
                - 9
                - 11
                - 49
                - 71
                - 98
                - 103
            "3":
                - 2
                - 13
            "4": 3.11.14
            "5": 0.23.1
            "6": 4.57.3
            "12": 0.23.1
            "13": linux-x86_64
